print('ola mundo') 
print('Goodnight menina')
print('Adorei sua cara de cretina')
print('Juliete tampando a retina')
print('Tá difícil de artista a rotina')
print('Escrevendo o que sinto na rima')
print('Afogando as mágoas no cash')
print('Igor Guilherme segue sem estresse')
print('Garota sexy já quer me ver')
print('Manda descer')
print('Verde combina com a Porsche e a paty')
print('A água potável é Don Perrie')
print('Chama a amiga que ama a quadrilha')
print('Que chama outra amiga pra vir se envolver')
print('Meu filho rico, cheiroso e bonito')
print('Já sabia disso antes de nascer')
print('Jogo do Corinthians, churrasco na vila')
print('Contraste com as gata que é lá da TV')
print('Que vem de longe pros drake só plug')
print('E as dama da night pro couro comer')
print('Eu de lacoste, cheirando a malote')
print('Investindo forte pro vento render')
print('O DJ Glenner mandando a batida')
print('Ela joga e rebola pro bonde')
print('Fire in gang house')
print('No speak english')
print('Há vários KM')
print('Tipo GTA, mas no modo real')
print('Dentro da BM')
print('Se amarra nos preto no luxo com cara de mal')
print('Há vários KM')
print('Tipo GTA, mas no modo real')
print('Dentro da BM')
print('Se amarra nos preto no luxo com cara de mal')
print('Há vários KM')
print('Tipo GTA, mas no modo real, uh')
print('Dentro da BM')
print('Se amarra nos preto com cara de mal')